project_id = "dsvpodsvrxwgfqnuojcz"

[functions.parse-document]
verify_jwt = true

[functions.chat-tutor]
verify_jwt = true

[functions.manage-collections]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.increment-usage]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
