// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsvpodsvrxwgfqnuojcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzdnBvZHN2cnh3Z2ZxbnVvamN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2NzIxMzYsImV4cCI6MjA4MTI0ODEzNn0.mTn_N720J1npC-oRQeFbCe4TMqJbb0DHhQ4QetYxmqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});